/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/routines/RoutineList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/routines/RoutineTile`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/ActivityList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/ActivityTile`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/RecordsList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/RecordsTile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routines` | `/routines`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/routines/RoutineList`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/routines/RoutineTile`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/history/ActivityList`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/history/ActivityTile`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/history/RecordsList`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/history/RecordsTile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/routines` | `/routines`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/routines/RoutineList${`?${string}` | `#${string}` | ''}` | `/../components/routines/RoutineTile${`?${string}` | `#${string}` | ''}` | `/../components/history/ActivityList${`?${string}` | `#${string}` | ''}` | `/../components/history/ActivityTile${`?${string}` | `#${string}` | ''}` | `/../components/history/RecordsList${`?${string}` | `#${string}` | ''}` | `/../components/history/RecordsTile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exercises${`?${string}` | `#${string}` | ''}` | `/exercises${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/routines${`?${string}` | `#${string}` | ''}` | `/routines${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workout${`?${string}` | `#${string}` | ''}` | `/workout${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/routines/RoutineList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/routines/RoutineTile`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/ActivityList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/ActivityTile`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/RecordsList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/RecordsTile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routines` | `/routines`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workout` | `/workout`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
