export const exercises = [
  {
    id: "1",
    name: "Pull-Up",
    primaryMuscle: "Back",
    secondaryMuscle: "Biceps",
    equipment: "Bodyweight",
    difficulty: "Intermediate",
  },
  {
    id: "2",
    name: "Barbell Squat",
    primaryMuscle: "Quadriceps",
    secondaryMuscle: "Glutes",
    equipment: "Barbell",
    difficulty: "Intermediate",
  },
  {
    id: "3",
    name: "Romanian Deadlift",
    primaryMuscle: "Hamstrings",
    secondaryMuscle: "Glutes",
    equipment: "Barbell",
    difficulty: "Intermediate",
  },
  {
    id: "4",
    name: "Flat Barbell Bench Press",
    primaryMuscle: "Chest",
    secondaryMuscle: "Triceps",
    equipment: "Barbell",
    difficulty: "Intermediate",
  },
  {
    id: "5",
    name: "Seated Cable Row",
    primaryMuscle: "Back",
    secondaryMuscle: "Rear Delts",
    equipment: "Cable Machine",
    difficulty: "Beginner",
  },
  {
    id: "6",
    name: "Dumbbell Lateral Raise",
    primaryMuscle: "Shoulders",
    secondaryMuscle: "Traps",
    equipment: "Dumbbells",
    difficulty: "Beginner",
  },
  {
    id: "7",
    name: "Cable Tricep Pushdown",
    primaryMuscle: "Triceps",
    secondaryMuscle: "Shoulders",
    equipment: "Cable Machine",
    difficulty: "Beginner",
  },
  {
    id: "8",
    name: "Incline Dumbbell Curl",
    primaryMuscle: "Biceps",
    secondaryMuscle: "Forearms",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
  },
  {
    id: "9",
    name: "Bulgarian Split Squat",
    primaryMuscle: "Quadriceps",
    secondaryMuscle: "Glutes",
    equipment: "Dumbbells",
    difficulty: "Advanced",
  },
  {
    id: "10",
    name: "Hanging Leg Raise",
    primaryMuscle: "Core",
    secondaryMuscle: "Hip Flexors",
    equipment: "Bodyweight",
    difficulty: "Intermediate",
  },
];
